#LOCAL http://localhost:3000/users
#REMOTE https://pos-backend-node-production.up.railway.app/users HTTP/1.1

#REMOTE
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTYsInVzZXJuYW1lIjoicHJ1ZWJhY2FqYTIiLCJyb2xlIjoxLCJpYXQiOjE2NzQ5NzQ2Mjh9.Xc4NpPdO2RsX0xiseHgJU29TUFltfYWwIqsbuccAgH4

{
    "name": "caja3",
    "username": "pruebacaja3",
    "password": "passpruebatoken",
    "role": 1
}

###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "gabriel",
    "lastName": "vejar",
    "username": "gabo7",
    "password": "passpruebatoken",
    "roleId": 4
}
