#LOCAL
POST http://localhost:3000/v1/users HTTP/1.1
Content-Type: application/json
# Authorization: Bearer 

{
    "first_name": "gabriel2",
    "last_name": "vejar2",
    "username": "gabo4",
    "password": "password",
    "role": "CASHIER"
}

###

#REMOTE
POST https://pos-backend-node-production.up.railway.app/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer 

{
    "first_name": "gabriel",
    "last_name": "vejar",
    "username": "gabo20",
    "password": "passpruebatoken",
    "role_id": 4
}
